# Generated by Django 6.0.2 on 2026-08-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
