# Generated by Django 6.0.2 on 2026-08-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_pos', '0003_alter_detalleventa_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='precio_costo_historico',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='producto_nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
