# Generated by Django 4.2.30 on 2026-09-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_pos', '0006_categoria_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
